### ISSUE TITLE
Basic Webpage Design

### ISSUE THREAD

**Issue by jmtiong** [NUSComputingDev/gfp#2]
A basic webpage design to display more information about the events for people

**Comment by Skaty** [comment]
Do you mean something like the details of GFP and everything?

How about Sign Up forms?

**Comment by jmtiong** [comment]
Hello! yup, that is what I meant. Basically it is a page to display information about the event.

As for the sign up form, it has a separate link for it

**Comment by Skaty** [comment]
Hmm, why wouldn't you want the sign-up form to be part of the app? Unless that is handled by a different team, I don't see the point in separating data collection that could be used during the GFP itself.

**Comment by Skaty** [comment]
gfp.nuscomputing.com
